from .contrastive import ContrastiveModel
from .concurrent_coordinate_ascent import ConcurrentCoordinateAscentModel
from .coordinate_ascent import CoordinateAscentModel
from .model import Model as AbstractModel